---
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.3.0
      hooks:
          - id: end-of-file-fixer
          - id: trailing-whitespace

    - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
      rev: v2.7.0
      hooks:
      - id: pretty-format-golang
        args: [--autofix]

    - repo: https://github.com/igorshubovych/markdownlint-cli
      rev: v0.33.0
      hooks:
          - id: markdownlint
            args: [--config, markdownlint_config.json, -fix]

    - repo: https://github.com/sirwart/ripsecrets
      rev: v0.1.5  # Use latest tag on GitHub
      hooks:
          - id: ripsecrets
