- id: requirements-checker
  name: Check Requirements File
  description: Validates the requirements*.txt files contain the packages present in the virtualenv.
    #  entry: requirements-checker
    #entry: foobar
    #language: script
    #  language: python
  entry: rq
  language: golang
  args: ["--foo"]
  types: [text]
