- id: requirements_checker
  name: Ensure virtualenv matches requirements.txt
  description: Validates the virtualenv modules match those defined in requirements.txt
  entry: requirements_checker
  language: golang
  args: []
  types: []
  always_run: true
  pass_filenames: false
